### ISSUE TITLE
Position entered for Prop 52 is showing on Prop 51

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WebApp#533]
### Steps to reproduce the problem (1, 2, 3...), including links
1. Enter a position 1 on one measure (not a problem on candidates) and post it.
2. Search for position 2 and go to it.
3. Your position 1 shows up as if you entered it for position 2.
   Your position 1 disappears from position 2 when you refresh the position 2 page.

**Comment by DaleMcGrew** [comment]
@ColettePhair can you verify that this is fixed now?

**Comment by zachmonteith** [comment]
Hey @DaleMcGrew, this is not fixed.  

It's measure_subtitle, which is a prop of all measures (or, a prop of all Props?  haha), and in this case, on the ballot page is being passed in (as far as I can tell) from routes/Ballot.jsx to components/ballot/BallotItemCompressed.jsx to MeasureItemCompressed.jsx.  I can't figure out why the wrong measure_subtitle is ONLY displaying for prop 52, and why it ALWAYS displays the subtitle for prop 51.  @kyleludlow is here with me, and on his ballot page, they didn't even appear sequentially (51 was out of order, farther down the ballot) but prop 52 still displayed the measure_subtitle for prop 51.

**Comment by kyleludlow** [comment]
Hey @DaleMcGrew,

What's super strange is that location seems to trigger this. When I set my location to Walnut Creek, the subtitle is correct. We tested out whether distance or common letter sequences trigger it but nothing seems consistent haha. Crazy mystery. Any thoughts? Could it be on the backend?

**Comment by DaleMcGrew** [comment]
Hi @niyatikothari when you get a moment can you see if you can reproduce this problem? Thank you.

**Comment by niyatikothari** [comment]
Hi Dale,

I will check and let you know.

Regards,
Niyati kothari

**Comment by niyatikothari** [comment]
Hi Dale,

I am able to reproduce this issue with below steps:


   1.

   Navigate to https://wevote.us/ballot
   2.

   Click on Proposition 51
   3.

   Title is “US 2016 General Election · California”
   4.

   Go Back to https://wevote.us/ballot
   5.

   Click on Proposition 52
   6. Title is “US 2016 General Election · California”



Regards,
Niyati Kothari

**Comment by DaleMcGrew** [comment]
Closing this issue.
